version: '3'
networks:
  net: 
services:
  mysql-database:
    image: mysql-database
    container_name: mysql-database
    ports:
      - 3306:3306
    networks:
      - net
  email-api:
    image: email-api
    container_name: email-api
    ports:
      - 8084:8080
    networks:
      - net
