version: '3'
networks:
  net: 
services:
  auth-api: # Authentication API (Spring)
    image: auth-api
    container_name: auth-api
    ports:
      - 8083:8080
    networks:
      - net
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      - mysql-database     
  mysql-database:
    image: mysql-database
    container_name: mysql-database
    ports:
      - 3306:3306
    networks:
      - net