version: '3'
networks:
  net:
    external: true
services:
  mysql-database:
    image: mysql-database
    container_name: mysql-database
    ports:
      - 3306:3306
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 256M
  email-api:
    image: email-api
    container_name: email-api
    ports:
      - 8084:8084
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 256M