version: '3'
networks:
  net:
    external: true
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres-scripts:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          memory: 256M
  email-api:
    image: email-api
    container_name: email-api
    ports:
      - 8084:8084
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 256M