FROM tomcat
LABEL maintainer="jovanibrasil@gmail.com"
USER root

RUN apt-get -y update && apt-get -y install netcat

ARG USERS_MYSQL_URL 
ARG USERS_MYSQL_USERNAME 
ARG USERS_MYSQL_PASSWORD
ARG RECAPTCHA_KEY_SECRET
ARG RECAPTCHA_KEY_SITE
ARG ENVIRONMENT
ARG FILE_NAME
ARG DBSERVICEPORT
ARG DBSERVICENAME

ENV USERS_MYSQL_URL=$USERS_MYSQL_URL
ENV USERS_MYSQL_USERNAME=$USERS_MYSQL_USERNAME
ENV USERS_MYSQL_PASSWORD=$USERS_MYSQL_PASSWORD
ENV ENVIRONMENT=$ENVIRONMENT
ENV RECAPTCHA_KEY_SECRET=$RECAPTCHA_KEY_SECRET
ENV RECAPTCHA_KEY_SITE=$RECAPTCHA_KEY_SITE
ENV FILE_NAME=${FILE_NAME}
ENV VAULT_HOST="vault-server"

ENV DBSERVICEPORT=$DBSERVICEPORT
ENV DBSERVICENAME=$DBSERVICENAME

COPY ./target/${FILE_NAME} /usr/local/tomcat/webapps/${FILE_NAME}
COPY ./scripts ./scripts

RUN sed -i 's/port="8080"/port="8083"/' /usr/local/tomcat/conf/server.xml

RUN if [ "$ENVIRONMENT" = "stage" ]; \
	then cp ./scripts/startup-dev.sh /startup.sh; \
	else cp ./scripts/startup-prod.sh /startup.sh;\
	fi

RUN rm ./scripts -rf
EXPOSE 8083

RUN ["chmod", "+x", "/startup.sh"]
CMD ["sh", "-c", "/startup.sh $DBSERVICENAME $DBSERVICEPORT"]
