captcha:
  keysecret: ${RECAPTCHA_KEY_SECRET}
  keysite: ${RECAPTCHA_KEY_SITE}
spring:
  application:
    name: auth-api
  flyway:
    baseline-on-migrate: true
    clean-on-validation-error: true
  profiles:
    active: '@activatedProperties@'
  boot:
    admin:
      client:
        url: http://localhost:8090  
management:
  endpoints:
    web:
      exposure:
        include: '*'
urls:
  blog:
    createuser: http://blog-api:8080/blog-api/users
    deleteuser: http://blog-api:8080/blog-api/users
  email:
    server:
      url: http://email-api:8080/email-api/emails
  notes:
    createuser: http://notes-api:8080/notes-api/users
    deleteuser: http://notes-api:8080/notes-api/users
    userconfirmationview: http://127.0.0.1:4200/confirmation
