captcha:
  recaptchakeysecret: ${RECAPTCHA_KEY_SECRET}
  recaptchakeysite: ${RECAPTCHA_KEY_SITE}
jwt:
  expiration: "63113904\t"
  secret: ${JWT_SECRET_KEY}
server:
  port: 8080
spring:
  datasource:
    plataform: postgres
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
  flyway:
    locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
urls:
  blog:
    createuser: https://jb-blog-api.herokuapp.com/users
    deleteuser: https://jb-blog-api.herokuapp.com/users
  email:
    server:
      url: https://master-email-api.herokuapp.com/emails
  notes:
    createuser: https://jb-notes-api.herokuapp.com/users
    deleteuser: https://jb-notes-api.herokuapp.com/users
    userconfirmationview: https://notes.jovanibrasil.com/confirmation
