captcha:
  recaptchakeysecret: ${RECAPTCHA_KEY_SECRET}
  recaptchakeysite: ${RECAPTCHA_KEY_SITE}
db:
  password: ${DB_PASSWORD}
  url: ${DB_URL}
  username: ${DB_USERNAME}
jwt:
  expiration: "63113904\t"
  secret: ${JWT_SECRET_KEY}
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  flyway:
    locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
urls:
  blog:
    createuser: http://apps-server:8080/blog-api/users
    deleteuser: http://apps-server:8080/blog-api/users
  email:
    server:
      url: https://master-email-api.herokuapp.com/emails
  notes:
    createuser: http://apps-server:8080/notes-api/users
    deleteuser: http://apps-server:8080/notes-api/users
    userconfirmationview: https://notes.jovanibrasil.com/confirmation
