jwt:
  expiration: 604800
  secret: MY_KEY
server:
  port: ${PORT:8083}
spring:
  rabbitmq:
    host: rabbitmq
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:  
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
            use_jdbc_metadata_defaults: false 
  datasource:
    plataform: postgres
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/usersdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    testWhileIdle: true
    test-on-borrow: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 