jwt:
  expiration: 604800
  secret: MY_KEY
server:
  port: 8083
spring:
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:  
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
            use_jdbc_metadata_defaults: false
  datasource:
    plataform: postgres
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/usersdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    testWhileIdle: true
    test-on-borrow: true
urls:
  blog:
    createuser: http://127.0.0.1:8081/users
    deleteuser: http://127.0.0.1:8081/users
  email:
    server:
      url: http://127.0.0.1:8084/emails
  notes:
    createuser: http://127.0.0.1:8082/users
    deleteuser: http://127.0.0.1:8082/users
    userconfirmationview: http://127.0.0.1:4200/confirmation
