jwt:
  expiration: 604800
  secret: MY_KEY
server:
  port: 8083
spring:
  datasource:
    password: root
    url: ${DATASOURCE_URL:jdbc:mysql://mysql-database:3306/usersdb}
    username: root
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
  jpa:
    hibernate:
      ddl-auto: none
